id: 1_Open_PaintJS
learningObjectives: 
- Going to PaintJS.app
hints:
- Google it
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Hey! Today you're going to draw an amazing circle, I just feel it."
        delay: 2000
      - text: "Once you're ready, please visit paintJS.app. let me know while you're finished"
        delay: 3500
startFlow:
  do:
  - actionId: ready_message
    params:
      person: keen
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
