id: 3_Admire_your_circle
learningObjectives: 
- Congratulate yourself on a job well done
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Wonderful! You have just created a beautiful circle. Bask in its glory. Once you're done - pat yourself on the back. You earned it. Are you ready?"
        delay: 1500
startFlow:
  do:
  - actionId: ready_message
    params:
      person: keen
trigger:
  type: user_ready_response
  flowNode:
    do:
    - actionId: finish_step
